### ISSUE TITLE
NuGet badge

### ISSUE THREAD

**Issue by jnm2** [buvinghausen/TaskTupleAwaiter#2]
What do you think about putting this in the readme? Makes it easier to navigate to the nuget.org page.
[![NuGet](https://img.shields.io/nuget/v/TaskTupleAwaiter.svg)](https://www.nuget.org/packages/TaskTupleAwaiter/)

```markdown
[![NuGet](https://img.shields.io/nuget/v/TaskTupleAwaiter.svg)](https://www.nuget.org/packages/TaskTupleAwaiter/)
```

**Comment by buvinghausen** [comment]
@jnm2 awesome suggestion and I have now implemented this change...
