### ISSUE TITLE
The first line of the package description is repeated twice

### ISSUE THREAD

**Issue by jnm2** [buvinghausen/TaskTupleAwaiter#20]
https://www.nuget.org/packages/TaskTupleAwaiter/1.2.2

In VS:

![image](https://user-images.githubusercontent.com/8040367/91486374-273a2e80-e87a-11ea-941a-b9b67ff0ceb1.png)

![image](https://user-images.githubusercontent.com/8040367/91486402-2ef9d300-e87a-11ea-9632-fc23ea256414.png)

**Comment by buvinghausen** [comment]
[1.2.3](https://github.com/buvinghausen/TaskTupleAwaiter/releases/tag/1.2.3)
